---
abstract: "Prepends CSS selectors to apply scope/context\r"
author:
  - 'Henry Van Styn <vanstyn@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Scopifier
requires:
  CSS::Tiny: 1.19
  Moo: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/vanstyn/CSS-Scopifier.git
version: 0.03
